# http://travis-ci.org/#!/mapix/cffs
language: python
python:
    - 2.7

install:
    - pip install pylint
    - pip install --use-mirrors coveralls

script:
    - pylint -E cffo

after_success:
    coveralls
